services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    ports:
      - '3552:3552'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - ${PROJECTS_DIRECTORY}:${PROJECTS_DIRECTORY}
    env_file:
      - .env
    environment:
      - APP_URL=https://arcane.${DOMAIN}
      - PUID=1000
      - PGID=1000
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arcane.rule=Host(`arcane.${DOMAIN}`)"
      - "traefik.http.routers.arcane.entrypoints=websecure"
      - "traefik.http.routers.arcane.tls=true"
      - "traefik.http.routers.arcane.tls.certresolver=letsencrypt"
      - "traefik.http.services.arcane.loadbalancer.server.port=3552"
      - "traefik.http.routers.arcane.middlewares=security-headers@file"

networks:
  proxy:
    external: true

volumes:
  arcane-data:
