---
- name: Add starship to .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED: starship"
    block: |
      eval "$(starship init bash)"
  when: bashrc_st.stat.exists

- name: Add starship to .zshrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED: starship"
    block: |
      eval "$(starship init zsh)"
  when: zshrc_st.stat.exists
