---
- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ brew_packages }}"
    path: "{{ linuxbrew_prefix }}/bin"
    state: present

- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.bashrc"
  register: bashrc_st

- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
  register: zshrc_st

- name: Configure tools in shell
  ansible.builtin.include_tasks: "config/{{ item }}.yml"
  loop: "{{ tools_with_config }}"
