services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "${PUID:-1000}:${PGID:-1000}"
    networks:
      - proxy
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - ${DATA_PATH}:/srv
      - filebrowser-database:/database
      - filebrowser-config:/config
    command:
      - --address=0.0.0.0
      - --port=80
      - --root=/srv
      - --database=/database/filebrowser.db
      - --noauth
      - --disable-exec
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

      - "traefik.http.routers.filebrowser.rule=Host(`files.${DOMAIN}`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filebrowser.service=filebrowser"

      - "traefik.http.routers.filebrowser.middlewares=tinyauth@docker"

networks:
  proxy:
    name: proxy
    external: true

volumes:
  filebrowser-database:
    name: filebrowser-database
  filebrowser-config:
    name: filebrowser-config
